sudo: required

service: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'PYTHON_EN=test' web python manage.py makemigrations
  - docker-compose exec --env 'PYTHON_EN=test' web python manage.py migrate
  - docker-compose exec --env 'PYTHON_EN=test' web python manage.test