# Generated by Django 3.0.2 on 2021-04-08 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 8), verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, verbose_name='習慣'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, default=0, verbose_name='作業量'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='workrecord.Book', verbose_name='習慣'),
        ),
    ]
