# Generated by Django 3.0.2 on 2021-04-08 15:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0002_auto_20210408_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 9, 0, 47, 13, 769224), verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='作業時間'),
        ),
        migrations.AddField(
            model_name='book',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 9, 0, 47, 13, 769224), verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
