# Generated by Django 3.0.2 on 2021-04-13 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0004_auto_20210412_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='achieve_day',
            field=models.IntegerField(default=0, verbose_name='達成日数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 14, 1, 10, 51, 701850), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 14, 1, 10, 51, 701850), verbose_name='開始時間'),
        ),
    ]
