# Generated by Django 3.0.2 on 2021-04-15 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workrecord', '0006_auto_20210414_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='習慣')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='作業時間')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('achieve_day', models.IntegerField(default=0, verbose_name='達成日数')),
                ('start_time', models.TimeField(default=datetime.datetime(2021, 4, 15, 23, 35, 47, 231829), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.datetime(2021, 4, 15, 23, 35, 47, 231829), verbose_name='終了時間')),
            ],
        ),
        migrations.RemoveField(
            model_name='impression',
            name='book',
        ),
        migrations.CreateModel(
            name='ContinuationDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workrecord.Habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='impression',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='workrecord.Habit', verbose_name='習慣'),
        ),
        migrations.AlterField(
            model_name='achieve',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workrecord.Habit'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
