# Generated by Django 3.0.2 on 2021-04-23 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0008_auto_20210417_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='finish_judge',
            field=models.BooleanField(default=False, verbose_name='達成'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 0, 53, 2, 621731), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 0, 53, 2, 621731), verbose_name='開始時間'),
        ),
    ]
