# Generated by Django 3.0.2 on 2021-04-23 16:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0009_auto_20210424_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 1, 33, 49, 522020), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 1, 33, 49, 522020), verbose_name='開始時間'),
        ),
    ]
