# Generated by Django 3.2.5 on 2021-07-03 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0012_auto_20210704_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 4, 1, 20, 33, 196978), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 4, 1, 20, 33, 196961), verbose_name='開始時間'),
        ),
    ]
