# Generated by Django 3.2.5 on 2021-07-04 21:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0013_auto_20210704_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='impression',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='impression',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='作業時間'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 5, 6, 49, 18, 425271), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 5, 6, 49, 18, 425253), verbose_name='開始時間'),
        ),
    ]
